-- =====================================================================
-- 05_ltv_by_channel.sql
-- =====================================================================
-- BUSINESS QUESTION:
-- "Which acquisition channels bring the highest-value customers over 
--  their first 30 days, not just the most users?"
--
-- WHY THIS MATTERS:
-- CAC by channel is meaningless without LTV by channel. A channel with 
-- $50 CAC and $40 LTV loses money. A channel with $80 CAC and $200 LTV
-- prints money. Most marketing dashboards show only acquisition counts —
-- this query closes that gap.
--
-- DATA LIMITATION (GA4 public dataset):
-- Revenue fields (item_revenue, price) are obfuscated to NULL in this
-- public dataset for privacy. We use PURCHASE COUNT as a proxy for LTV.
-- In production with real GA4 export, replace `SUM(1)` with 
-- `SUM(item.item_revenue_in_usd)` from the items array.
--
-- DATASET: bigquery-public-data.ga4_obfuscated_sample_ecommerce
-- DATE RANGE: 2021-01-01 to 2021-01-31 (30-day window)
-- =====================================================================


-- ---------------------------------------------------------------------
-- QUERY 1: Per-user acquisition channel + purchase count (30-day LTV proxy)
-- ---------------------------------------------------------------------
-- For each user:
--   1. Find their FIRST visit and the channel that brought them
--   2. Count their purchases in the 30-day window from first visit
-- This gives us a per-user LTV proxy ready for channel aggregation.
-- ---------------------------------------------------------------------

WITH first_touch AS (
  -- Step 1: each user's acquisition channel = source/medium of their first_visit
  SELECT
    user_pseudo_id,
    -- Their first event timestamp
    MIN(event_timestamp) AS first_visit_ts,
    -- traffic_source is GA4's first-touch attribution (top-level STRUCT)
    ANY_VALUE(traffic_source.source) AS acq_source,
    ANY_VALUE(traffic_source.medium) AS acq_medium
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20210101' AND '20210131'
    AND event_name = 'first_visit'
  GROUP BY user_pseudo_id
),

user_purchases AS (
  -- Step 2: count purchases per user in the 30-day window from first visit
  SELECT
    e.user_pseudo_id,
    COUNT(*) AS purchase_count
    -- In production with real revenue:
    -- SUM((SELECT SUM(item.item_revenue_in_usd) FROM UNNEST(e.items) AS item)) AS total_revenue
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*` e
  JOIN first_touch ft USING (user_pseudo_id)
  WHERE _TABLE_SUFFIX BETWEEN '20210101' AND '20210131'
    AND e.event_name = 'purchase'
    -- Only count purchases within 30 days of first visit
    AND e.event_timestamp <= ft.first_visit_ts + (30 * 24 * 60 * 60 * 1000000)  -- 30 days in microseconds
  GROUP BY e.user_pseudo_id
)

SELECT
  ft.user_pseudo_id,
  ft.acq_source,
  ft.acq_medium,
  COALESCE(up.purchase_count, 0) AS purchases_30d
FROM first_touch ft
LEFT JOIN user_purchases up USING (user_pseudo_id)
ORDER BY purchases_30d DESC
LIMIT 20;

-- Expected output: per-user table with their first channel and purchase count.
-- Most users will have 0 purchases (browsers), some 1, very few 2+.


-- ---------------------------------------------------------------------
-- QUERY 2: LTV proxy by acquisition channel (the actionable view)
-- ---------------------------------------------------------------------
-- Aggregate per-user data up to channel level. Show:
--   - new_users:        how many users this channel acquired
--   - converters:       how many of those made >= 1 purchase
--   - total_purchases:  total purchases generated by users from this channel
--   - conversion_rate:  % of acquired users who bought
--   - avg_ltv_proxy:    avg purchases per acquired user (THE KEY METRIC)
--
-- avg_ltv_proxy = total_purchases / new_users
-- This tells you: "every user from channel X is worth N purchases on avg"
-- ---------------------------------------------------------------------

WITH first_touch AS (
  SELECT
    user_pseudo_id,
    MIN(event_timestamp) AS first_visit_ts,
    ANY_VALUE(traffic_source.source) AS acq_source,
    ANY_VALUE(traffic_source.medium) AS acq_medium
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*`
  WHERE _TABLE_SUFFIX BETWEEN '20210101' AND '20210131'
    AND event_name = 'first_visit'
  GROUP BY user_pseudo_id
),

user_purchases AS (
  SELECT
    e.user_pseudo_id,
    COUNT(*) AS purchase_count
  FROM `bigquery-public-data.ga4_obfuscated_sample_ecommerce.events_*` e
  JOIN first_touch ft USING (user_pseudo_id)
  WHERE _TABLE_SUFFIX BETWEEN '20210101' AND '20210131'
    AND e.event_name = 'purchase'
    AND e.event_timestamp <= ft.first_visit_ts + (30 * 24 * 60 * 60 * 1000000)
  GROUP BY e.user_pseudo_id
)

SELECT
  ft.acq_medium AS medium,
  ft.acq_source AS source,
  COUNT(DISTINCT ft.user_pseudo_id) AS new_users,
  COUNT(DISTINCT IF(up.purchase_count > 0, ft.user_pseudo_id, NULL)) AS converters,
  COALESCE(SUM(up.purchase_count), 0) AS total_purchases,
  ROUND(
    COUNT(DISTINCT IF(up.purchase_count > 0, ft.user_pseudo_id, NULL)) * 100.0 
    / NULLIF(COUNT(DISTINCT ft.user_pseudo_id), 0), 
    2
  ) AS conversion_rate_pct,
  -- LTV PROXY: average purchases per acquired user (zeros included)
  ROUND(
    COALESCE(SUM(up.purchase_count), 0) * 1.0 
    / NULLIF(COUNT(DISTINCT ft.user_pseudo_id), 0), 
    4
  ) AS avg_ltv_proxy
FROM first_touch ft
LEFT JOIN user_purchases up USING (user_pseudo_id)
GROUP BY medium, source
HAVING new_users >= 50  -- exclude tiny channels with no statistical weight
ORDER BY avg_ltv_proxy DESC
LIMIT 20;

-- Expected output (Jan 2021, 30-day window, channels with >=50 users):
-- medium    | source     | new_users | converters | purchases | conv_rate | avg_ltv_proxy
-- referral  | <Other>    | 8,239     | 72         | 91        | 0.87%     | 0.0110
-- (none)    | (direct)   | 21,283    | 198        | 235       | 0.93%     | 0.0110
-- <Other>   | <Other>    | 16,070    | 146        | 164       | 0.91%     | 0.0102
-- organic   | <Other>    | 2,995     | 25         | 28        | 0.83%     | 0.0093
--
-- INSIGHT: All channels show similar LTV proxy (~0.01 purchases/user/30d).
-- This means channel quality is comparable — the actionable difference 
-- is CAC (cost per acquisition), not LTV. If two channels have equal 
-- LTV but channel A costs 1/5 of channel B, A wins economically.
--
-- DIRECT (21K users, same LTV) is your BRAND CAPITAL — free traffic 
-- that converts at the same rate as paid. Investment here is brand 
-- awareness ROI, not performance ROI. Hardest to grow, highest leverage.
--
-- ORGANIC has LOWEST LTV (0.0093) — counterintuitive. Likely "research 
-- mode" users who read, compare, don't buy on first visit. Worth 
-- breaking down further: branded organic vs generic organic LTV likely 
-- differs by 3-5x in production data.


-- =====================================================================
-- EDGE CASES TO REMEMBER:
-- =====================================================================
-- 1. Obfuscated dataset: real revenue is NULL here. In production GA4 
--    export, replace COUNT(*) AS purchase_count with:
--      SUM((SELECT SUM(item.item_revenue_in_usd) 
--           FROM UNNEST(e.items) AS item)) AS revenue
--
-- 2. 30-day window cutoff: cohorts late in the data range have 
--    incomplete windows. For honest comparison, only include cohorts 
--    with full 30-day forward window (e.g., first_visit before Jan 1 
--    if data ends Jan 31).
--
-- 3. avg_ltv_proxy includes ZEROS: this is correct for LTV (most users 
--    don't buy). If you want "ARPU among purchasers only", divide 
--    total_purchases by converters instead of new_users.
--
-- 4. HAVING new_users >= 50: small channels produce noisy LTV. Filter 
--    them out OR show them with a "low confidence" flag in production.
--
-- 5. first_visit reliability: this event can be missed if cookies clear.
--    Alternative: use MIN(event_timestamp) per user as proxy for first 
--    visit (less precise but no missing-event risk).
--
-- 6. Microsecond math: GA4 event_timestamp is microseconds since epoch.
--    30 days = 30 * 24 * 60 * 60 * 1,000,000 microseconds. Get this 
--    wrong and your window is off by orders of magnitude.
-- =====================================================================